// import { Geist, Geist_Mono } from "next/font/google";
import Header from "./Components/page";
import localFont from "next/font/local";
import Footer from "./Footer/page";
import Home from "./Home/page";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

// const segoe = localFont({
//   src: "../../public/font/segoe-ui-this/segoeuithisi.ttf",
//   variable: "--font-segoe",
// });

// className={`${segoe.variable} ${serif.variable}`}

// const serif = localFont({
//   src: "../../public/font/georgia-2/georgiaz.ttf",
//   variable: "--font-serif",
// });

export const metadata={
  title:"Engage & retain more homeowners - Haven",
  description:'Generated by the create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
        {/* <meta
          name="description"
          content="Engage & retain more homeowners - Haven"
        /> */}
        <link rel="icon" href="/assets/logo.png" />
      </head>
      <body>
        <Header />
        <Home />
        {children}
        <Footer />
      </body>
    </html>
  );
}
